"""Updated the nullable false full_name in table users

Revision ID: 8dca0ad116ea
Revises: 2bf534b6806b
Create Date: 2024-04-19 18:29:28.184075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dca0ad116ea'
down_revision: Union[str, None] = '2bf534b6806b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
