name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - features-branch
  pull_request:
    branches:
      - features-branch
jobs:
  build-deploy:
    name: Build and Deploy FastAPI App     
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 #for checking repository
      - name: Set up Python
      
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install install -r requirement.txt 

      - name: Deploy FastAPI App
      run: |
        # Replace this with your deployment commands
        ssh -o StrictHostKeyChecking=no user@example.com 'cd /path/to/app && git pull && systemctl restart myapp.service'

    - name: Extract Deployed URL
      run: |
        # Assuming your FastAPI app is deployed on a specific port (e.g., 8000)
        DEPLOYED_URL="http://example.com:8000"  # Modify this with your actual deployed URL
        echo "::set-output name=url::$DEPLOYED_URL"

    - name: Store Deployed URL
      id: store_url
      run: echo "Deployed URL: $DEPLOYED_URL"

    - name: Set URL as Output
      run: echo "::set-output name=url::$DEPLOYED_URL"
      env:
        DEPLOYED_URL: $DEPLOYED_URL

    - name: Set up SSH for deployment
      uses: webfactory/ssh-agent@v0.5.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}    

  notify:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Get Deployed URL
      run: echo "Deployed URL: ${{ needs.deploy.outputs.url }}"    
